### ISSUE TITLE
[Basic][Evmos] Add deployment scripts for the contracts

### ISSUE THREAD

**Issue by artur-abliazimov** [warden-protocol/wardenprotocol#1012]

**Comment by pitasi** [comment]
in this case the contracts = the Factory contract, right?

I agree that we need some tooling around Solidity contracts, equivalent to the `just compile` and `just localnet deploy-contract` commands

**Comment by mn13** [comment]
> in this case the contracts = the Factory contract, right?

Yes, you're right

**Comment by artur-abliazimov** [comment]
> in this case the contracts = the Factory contract, right?
> 
> I agree that we need some tooling around Solidity contracts, equivalent to the `just compile` and `just localnet deploy-contract` commands

Yes, since we decided to use `foundry` as a dev environment this will be a forge [script to deploy](https://book.getfoundry.sh/tutorials/solidity-scripting) the `Factory` and maybe a couple of other scripts to maintain/manage it.
