### ISSUE TITLE
Generalizing "Orders" to arbitrary transactions

### ISSUE THREAD

**Issue by warden-dev1** [warden-protocol/wardenprotocol#1126]
For the basic agent we need to investigate what we can support buy/sell transactions with minor adjustments of the basic agent:
1. Uniswap 
2. Curve DEX 
3. Balancer 
4. Sushi 
5. Bancor 
6. Pancake Swap 
7. 1Inch 
8. Loopring 
9. Thorchain 
10. IDEX

**Note** We to support them if we can easily add them. If it requires custom adjustments or more on-top work I'd prefer to reiterate.

**Comment by backsapc** [comment]
- [x] Create a list of DEXes available in Sepolia Testnet
- [x] Create a list of DEXes with the same method signature as in Uniswap (basically forks) - https://github.com/warden-protocol/wardenprotocol/blob/96d73ad71373fc0296cadea108269d331a53fccf/solidity/orders/src/BasicOrder.sol#L33
- [x] Create a list of DEXes already implemented adapters
- [x] Estimation

**Comment by mn13** [comment]
What we can do now:

- [ ] Create adapter for UniswapV2 (just move this logic from BasicOrder to separate contract)
- [ ] Create adapter for Balancer
- [ ] Use adapters in OrderFactory and in BasicOrders

**Comment by mn13** [comment]
Decide to use off chain builded transactions, which also close this case https://github.com/warden-protocol/wardenprotocol/issues/1132
