### ISSUE TITLE
gitbub link shows discord image

### ISSUE THREAD

**Issue by sushant992** [warden-protocol/wardenprotocol#119]
![Warden Protocol explorer, powered by Ping, tuned by Paramormal Bros  - Google Chrome 25-03-2024 12_07_37](https://github.com/warden-protocol/wardenprotocol/assets/160864284/03a286fa-f0f2-499c-8819-7a843aeca480)

in warden protocol explorer website left side down corner , gitgub website shows discord logo which is incorrect , Thankyou !

**Comment by pitasi** [comment]
Hey, thanks for reporting this but this explorer is not operated by us. I'll forward this to Paranormal brothers and close this for now.
