### ISSUE TITLE
CosmWasm 2.0

### ISSUE THREAD

**Issue by pitasi** [warden-protocol/wardenprotocol#198]
It looks that CosmWasm 2.0 has been released:

- https://github.com/CosmWasm/cosmwasm/releases

but wasmd hasn't been updated yet:

- https://github.com/CosmWasm/wasmd/releases

Let's wait for it to be updated, but I'm opening this issue to keep track of their progress, since we probably want to avoid doing a lot of work right now just to later realize that there are tons of breaking changes (which, btw, I don't know how "breaking" 2.0 is).

**Comment by backsapc** [comment]
It seems that wasmd of version 0.51 has been added to the project already. May close the issue.

**Comment by pitasi** [comment]
thanks, you're right
