### ISSUE TITLE
Add math operators to Shield language

### ISSUE THREAD

**Issue by pitasi** [warden-protocol/wardenprotocol#260]
We should add new operators to the shield language:

Basic math operators: `+`, `-`, `*`, `/`.

~~Basic comparison operators: `>`, `<`, `>=`, `<=`, `==`, `!=`.~~

I think that we should avoid dealing with floating numbers, as we're often dealing with prices and other financial values. Let's stick with integers, and possibly use `BigInt`s instead of `int64` while evaluating the results.

**Comment by pitasi** [comment]
I partially covered this issue with https://github.com/warden-protocol/wardenprotocol/pull/292 (comparison operators).

**Comment by optifat** [comment]
@Pitasi I'd like to start implementing this feature

Do I understand it correctly, that I need to do something similar to #292 PR, but for evaluator only?

**Comment by pitasi** [comment]
We need to add these operators:

> Basic math operators: `+`, `-`, `*`, `/`.

it involves adding the token types and adding support to the evaluator. Please also add some tests to ensure they work correctly.

**Comment by optifat** [comment]
> I need to do something similar to [#292](https://github.com/warden-protocol/wardenprotocol/pull/292) PR

I meant if the similar scope is sufficient enough for this feature or do I need to do something else?
I ask this because I'm not that familiar with the code and may miss something crucial

**Comment by pitasi** [comment]
It should be enough but let me know if need any help :)
