### ISSUE TITLE
Intents "Analyzers" platform

### ISSUE THREAD

**Issue by pitasi** [warden-protocol/wardenprotocol#262]
A great addition to our intent engine would be the ability for users to write conditions based on the transaction they're asking to sign.

Currently, we interpret the signature request payload with `SignMethods`. Users are able to specify, for example, the "Ethereum SignMethod" and the input payload will be parsed as an Ethereum unsigned transaction. Some metadata can be extracted from it (amount, to, etc.).

We're not doing it yet, but this metadata can be put in the shield evaluator environment. Users could write intents referencing the extracted metadata.

What I would like to have instead is a CosmWasm contract that does this job. Instead of specifying a SignMethod from a fixed enum, with each SignMethod handler embedded in wardend, the users could specify a list of smart contract addresses that parses the input payload and provides the same metadata.

This is a paradigm shift, as we allow 3rd party developers to build their own "Metadata Providers" (do you have a better name?). For example, we can have a 3rd party developer add support for parsing Solana transactions or who knows what, as long as the parser can be written as a CosmWasm contract.

The flow would look like this:
- user sends a MsgNewSignatureRequest, specifying one or more contracts (instead of SignMethod)
- the msg server handler from the Cosmos SDK module invokes the smart contracts and receive the execution results in a standardized format. It'll store the metadata in the Action, as part of the frozen intent definition.
- every time the Action is evaluated, the shield's execution environment will read the metadata present in the Action

**Comment by pitasi** [comment]
I'll rename "Metadata Parsers" => "Analyzers"

it's shorter and imho more evocative

**Comment by mn13** [comment]
> receive the execution results in a standardized format

Do you have any thoughts about this format, how it may looks and what it should describe?

**Comment by pitasi** [comment]
> > receive the execution results in a standardized format
> 
> Do you have any thoughts about this format, how it may looks and what it should describe?

yeah good question!

The contract should return a collection of key-values. The key should be a string (it will be an identifier in the shield language), and the value could be any supported type in the shield AST (i.e. integers and booleans, for now).

By default, CosmWasm returns the message in JSON format to the SDK. I thought of reusing this encoding, but there is no easy way of doing something like this in Rust:

```go
type AnalyzerResult struct {
    Values []KV
}

type KV struct {
    Key string
    Value any
}
```

So what I did in #279 instead is to have a custom JSON object like, for the sample contract:

```rs
#[cw_serde]
pub struct AnalyzeResult {
    pub length: u64,
}
```

that will serialize into a JSON like this:
```json
{ "length": 2 }
```

Now, from the SDK module I'm unmarshalling this JSON into a `map[string]any`, then I have a type-switch to do a type check of the `any` value and converting it into the proper AST node.

In the example above I would have a key named `length` and a value `float64(2)`. I check that the float64 is actually an integer and finally I'll convert it to an `IntegerLiteral` of shield's AST.

---

What I'm doing now is to get this a step further: beside key-value pairs I want analyzer contracts to return an optional `data_for_signing` binary, so the new AnalyzerResult looks like this:


```rs
// common result to all analyzers:
#[cw_serde]
pub struct AnalyzeResult<T> {
    pub data_for_signing: Option<Binary>,
    pub result: T,
}

// specific for my basic-analyzer, will be the <T> above:
#[cw_serde]
pub struct BasicAnalyzerResult {
    pub length: u64,
}
```

If an analyzer returns a `data_for_signing`, it will replace the `DataForSigning` field on the user request. The `result` field is parsed by the Go code described above.

Do you have other ideas or see any flaws in that?

**Comment by mn13** [comment]
Wow! Thanks for examples, it really helps.
My suggestion for now, as before for v1 intents, is to limit structure size, but I can't provide the way to do it on contract side. May be it's just can be done in go part.

Another potential problem is that user should trust the contract. What if 3rd party contracts will parse input and return `AnalyzeResult` but also make a transfer from the caller?

**Comment by pitasi** [comment]
> My suggestion for now, as before for v1 intents, is to limit structure size, but I can't provide the way to do it on contract side. May be it's just can be done in go part.

yeah I think #267 already captures that, the intent per-se might have a hard limit. I think the gas cost already disincentivizes to abuse calling too many smart contracts



> Another potential problem is that user should trust the contract. What if 3rd party contracts will parse input and return `AnalyzeResult` but also make a transfer from the caller?

this is correct, the user in its Intent references a contract so it needs to be trusted (note that this always apply when you use a smart contract on any chain). I don't think a cosmwasm contract can initiate a transfer, but I might be wrong, if there's a way to limit capabilities of specific contracts we should look into that.

**Comment by mn13** [comment]
>  I don't think a cosmwasm contract can initiate a transfer

You're right, funds are being transferred only if `coins` argument [is present](https://github.com/CosmWasm/wasmd/blob/8841505750248c005dcb23da9ff8d8e7585487c2/x/wasm/keeper/keeper.go#L400), I see in the [PR](https://github.com/warden-protocol/wardenprotocol/pull/279) that you're using nil for that, so all good
