### ISSUE TITLE
Axelar bridge

### ISSUE THREAD

**Issue by pitasi** [warden-protocol/wardenprotocol#269]
DoD:
- use the Warden-Axelar IBC channel to bridge ETH and any ERC-20 token to Warden Protocol
- integrate Axelar's [GMP](https://docs.axelar.dev/dev/general-message-passing/overview) to be able to invoke Warden Protocol's CosmWasm contracts from other chains (e.g. Ethereum)

**Comment by pitasi** [comment]
work to integrate with GMP started in #231

**Comment by artur-abliazimov** [comment]
3 ways of sending tokens cross-chain with the Axelar: https://docs.axelar.dev/dev/send-tokens/introduction. Need to explore. Will add more details here.

uausdc from Ethereum to Warden using the deposit address approach:
https://sepolia.etherscan.io/tx/0x379890ff7af5a0b1a8abb4d196c52ec8be9fe4260932eb88515e6811ef73bc19
https://testnet.axelarscan.io/transfer/0x0481b0e369d2b4784ae89f7c4324f61c5a59c20c83cfdc2f49397e50ad5277e7

uausdc from Warden to Ethereum using the deposit address approach:
https://testnet.warden.explorers.guru/transaction/2F673AD149039E04C23715AF9FD752014E14FBFCDF8E7023513DF045B3F5E3B6?height=886316

uausdc from Ethereum to Warden using the JS SDK sendToken method:
https://sepolia.etherscan.io/tx/0xb919ef241932b65990f562f9a05cf86a9e1f69d672b3240201be435ab05a3183
https://testnet.axelarscan.io/transfer/0xb919ef241932b65990f562f9a05cf86a9e1f69d672b3240201be435ab05a3183
