### ISSUE TITLE
Proposals response not full

### ISSUE THREAD

**Issue by PositivaLab** [warden-protocol/wardenprotocol#273]
```
curl -s http://localhost:1317/cosmos/gov/v1/proposals/2 | jq
{
  "proposal": {
    "id": "2",
    "messages": [],
    "status": "PROPOSAL_STATUS_DEPOSIT_PERIOD",
    ... bla-bla-bla...
```

same at websocket:
```
{
    '@type': '/cosmos.gov.v1.MsgSubmitProposal',
    'messages': [],
    .....
```

Pay attention, that "messages" block is empty. But it must be filled with proposal params data by default, something do not work.
Should be like:

```
"messages": [
        {
          "@type": "/cosmos.gov.v1.MsgExecLegacyContent",
          "content": {
            "@type": "/ibc.core.client.v1.ClientUpdateProposal",
            "title": "Replace expired dydx client",
            "description": "This proposal replaces the expired dydx IBC client with a new one",
            "subject_client_id": "07-tendermint-14",
            "substitute_client_id": "07-tendermint-27"
          },
          "authority": "persistence10d07y265gmmuvt4z0w9aw880jnsr700j5w4kch"
        }
      ],
```

or

```
 "messages": [
        {
          "@type": "/cosmos.upgrade.v1beta1.MsgSoftwareUpgrade",
          "authority": "persistence10d07y265gmmuvt4z0w9aw880jnsr700j5w4kch",
          "plan": {
            "name": "v11.10.0-rc0",
            "time": "0001-01-01T00:00:00Z",
            "height": "5012500",
            "info": "https://raw.githubusercontent.com/......",
            "upgraded_client_state": null
          }
        }
      ],
```

This part of proposal stores proposal type, upgrade plan (in case of Software upgrade proposal), client id's (in case of IBC client update), etc.
It's VERY important part to work with, for chain apps developers. Current state does not allow to implement important apps functions.

**Comment by pitasi** [comment]
Hey @ParanormalBrothers, interesting!

Can you tell me if you're testing locally, and how did you create the proposal?

I see that on Buenavista testnet we have two proposals:

1. looks good to me:
```
curl https://api.buenavista.wardenprotocol.org/cosmos/gov/v1/proposals/1 | jq

{
  "proposal": {
    "id": "1",
    "messages": [
      {
        "@type": "/cosmos.slashing.v1beta1.MsgUpdateParams",
        "authority": "warden10d07y265gmmuvt4z0w9aw880jnsr700j2vgu38",
        "params": {
          "signed_blocks_window": "10000",
          "min_signed_per_window": "0.500000000000000000",
          "downtime_jail_duration": "600s",
          "slash_fraction_double_sign": "0.050000000000000000",
          "slash_fraction_downtime": "0.010000000000000000"
        }
      }
    ],
    ...
```

2. and a second one that probably was created as a test without any message:

```
curl https://api.buenavista.wardenprotocol.org/cosmos/gov/v1/proposals/2 | jq

{
  "proposal": {
    "id": "2",
    "messages": [],
    ...

```

to me it looks like the second gov proposal was created on purpose without messages or maybe without using `wardend` properly. So it doesn't look like a bug on our side.

If you can tell me more about what you did and what you expected to happen instead, I'll be glad to help!

**Comment by PositivaLab** [comment]
By drafting proposal (tx gov draft-proposal).

Here are my drafts for it:

```
$ cat draft_proposal.json
{
 "metadata": "ipfs://CID",
 "deposit": "9000000uward",
 "title": "Test proposal. No need to vote.",
 "summary": "This proposal is for testing only, it dosen't change anything. So, no need to vote.",
 "expedited": false
}
```

```
$ cat draft_metadata.json
{
 "title": "Test proposal. No need to vote.",
 "authors": [
  "Mark"
 ],
 "summary": "This proposal is for testing only, it dosen't change anything. So, no need to vote.",
 "details": "No details for this proposal",
 "proposal_forum_url": "http://test.net",
 "vote_option_context": ""
}
```

This is basic text proposal. No params change. But anyway, even in text proposal must be "messages": [{"@type":... that shows that it's text proposal.

**Comment by pitasi** [comment]
Thanks for the additional information. This is the intended behavior for "TextProposal", at least with the `x/gov` module v1 (I'm not sure if it was different in v1beta1).

I'm going to close this, if you think something can be done better please report it to https://github.com/cosmos/cosmos-sdk, as they're the ones developing the `x/gov` module :)
