### ISSUE TITLE
Lack of validation in advanced intents condition field

### ISSUE THREAD

**Issue by 4uctorah** [warden-protocol/wardenprotocol#303]
1. A warning about the need for a second condition is required

![Image](https://github.com/warden-protocol/wardenprotocol/assets/59832414/d5be0a37-2afd-4c0b-803d-d11e04c73bac)

2. A warning about using unexpected address is required

![Image](https://github.com/warden-protocol/wardenprotocol/assets/59832414/84720c62-d54d-463d-b332-628c1980fbc5)

3. A warning about the need for use all addresses is required

![Image](https://github.com/warden-protocol/wardenprotocol/assets/59832414/84373a9c-e679-4ce5-8099-459519d7507a)

4.  Validation should be fired when ANY has the format - ANY [NUMBER] (ADR1, ADr2)

![Image](https://github.com/warden-protocol/wardenprotocol/assets/59832414/0e723dd3-f3ee-4415-b7ab-ff7db679ac37)

**Comment by 4uctorah** [comment]
1, 2 fixed
3, 4 reproduced

**Comment by alex-nax** [comment]
3, 4 are not bugs
