### ISSUE TITLE
shield: move from "int" to big.Int

### ISSUE THREAD

**Issue by pitasi** [warden-protocol/wardenprotocol#327]
Internally in the shield interpreter we should be able to parse and deal with big numbers (this spans from the lexer to the evaluator).

I think it's fine to use the stdlib `big.Int`. Add unit tests.

**Comment by optifat** [comment]
Are you suggesting to replace `int64` with `big.Int` completely or rather making conversion one to another for some internal actions?

**Comment by pitasi** [comment]
yeah I would use `big.Int` all the times
