### ISSUE TITLE
App address should display the application name and logo when added to the whitelist

### ISSUE THREAD

**Issue by 4uctorah** [warden-protocol/wardenprotocol#357]
If a user adds a target address for the following apps, Spaceward should recognize the address and show the app name and icon:
- Uniswap
- Squid
- Osmosis
- PancakeSwap
- BitBond
- CowSwap

![Image](https://github.com/warden-protocol/wardenprotocol/assets/59832414/76c3984c-fd55-4de9-af8e-8cead7612433)

**Comment by alex-nax** [comment]
For now we use hardcoded values https://github.com/warden-protocol/wardenprotocol/blob/main/spaceward/src/lib/eth.ts#L34
Later when ready we'll use API
