### ISSUE TITLE
Space cannot be created on devnet

### ISSUE THREAD

**Issue by 4uctorah** [warden-protocol/wardenprotocol#380]
![Image](https://github.com/warden-protocol/wardenprotocol/assets/59832414/cd50145e-5395-4074-b6be-910ed3e14d08)

**Comment by pitasi** [comment]
@jlehtimaki can you check the Spaceward env vars to see if the chain ID is correct? It should be `warden`.

**Comment by jlehtimaki** [comment]
> @jlehtimaki can you check the Spaceward env vars to see if the chain ID is correct? It should be `warden`.

It was set as `wardenprotocol`, fix applied and should show up soon.

**Comment by pitasi** [comment]
@4uctorah can you check if it's working correctly now? 

if not, it's possible that you'll have to remove Warden Protocol from your Keplr chains and refresh the page
