### ISSUE TITLE
Tagging in wardenprotocol does not start build process

### ISSUE THREAD

**Issue by jlehtimaki** [warden-protocol/wardenprotocol#383]
When we tag: e.g. faucet/v2.0.1 it needs to trigger a build process with the correct tag in place.
This needs to happen in all the projects in the repository:
- faucet/v* -> trigger faucet build
- wardend/v* -> trigger wardend build
- spaceward/v* -> trigger spaceward build
- wardenkms/v*

**Comment by zavertiaev** [comment]
Do I understand correctly that the build by tag should be in addition to the existing build? That is, the old build from `github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')` remains as it is?
