### ISSUE TITLE
Max button, link on validator doesn't work and no suggest in staking modal

### ISSUE THREAD

**Issue by 4uctorah** [warden-protocol/wardenprotocol#389]
Also modal doesn't closing if I click outside window

![Image](https://github.com/warden-protocol/wardenprotocol/assets/59832414/59729cf2-ee8a-4f12-b359-c3ac3e3c2c14)

**Comment by alex-nax** [comment]
Fix in https://github.com/warden-protocol/wardenprotocol/pull/463
