### ISSUE TITLE
No validation in staking modal

### ISSUE THREAD

**Issue by 4uctorah** [warden-protocol/wardenprotocol#393]
And you can sign a transaction if it has less than 15 digits in it

![Image](https://github.com/warden-protocol/wardenprotocol/assets/59832414/50c4974c-cad8-403d-9a2f-378c2cf96450)

![Image](https://github.com/warden-protocol/wardenprotocol/assets/59832414/770da57b-5bf8-4363-a33f-971eb8b708a1)

**Comment by alex-nax** [comment]
fixed in https://github.com/warden-protocol/wardenprotocol/pull/427
