### ISSUE TITLE
Unexpected metadata title and discription of proposal in governance

### ISSUE THREAD

**Issue by 4uctorah** [warden-protocol/wardenprotocol#418]
![Image](https://github.com/warden-protocol/wardenprotocol/assets/59832414/92b73649-dddf-435f-8ade-23b2cbd79813)

![Image](https://github.com/warden-protocol/wardenprotocol/assets/59832414/0881d037-81a6-4669-8b43-7d9ca428a4bb)

**Comment by alex-nax** [comment]
Default proposals were created with incorrect metadata, should work okay with correctly created proposals
