### ISSUE TITLE
Add x/act integration test for adding/removing owners

### ISSUE THREAD

**Issue by pitasi** [warden-protocol/wardenprotocol#495]
In the justfile, create a new snapshot copy pasting snapshot-base into snapshot-many-users. I.e. add commands like this:

```
  wardend keys add alice --keyring-backend test --home $WARDEND_HOME > /dev/null
  wardend keys add bob --keyring-backend test --home $WARDEND_HOME > /dev/null
  wardend keys add charlie --keyring-backend test --home $WARDEND_HOME > /dev/null
  wardend keys add dave --keyring-backend test --home $WARDEND_HOME > /dev/null
  wardend keys add erin --keyring-backend test --home $WARDEND_HOME > /dev/null
  wardend keys add frank --keyring-backend test --home $WARDEND_HOME > /dev/null
```

Be sure to fund at least some of them with:

```
  wardend genesis gentx alice 1000000000uward --keyring-backend test --home $WARDEND_HOME
  wardend genesis gentx bob 1000000000uward --keyring-backend test --home $WARDEND_HOME
  wardend genesis gentx charlie 1000000000uward --keyring-backend test --home $WARDEND_HOME
```

Create at least one space for Alice:

```
  wardend genesis add-genesis-space $(wardend keys show -a alice --keyring-backend test --home $WARDEND_HOME) --home $WARDEND_HOME
```

We'll be using this snapshot for different test cases involving many subset of users.

---

Then, add a new test case under "tests" that starts from the new snapshot. Check the existing test cases for reference. The new test should do:

- bob adds himself as an owner to Space 1
- < check bob doesn't get added as a space owner yet, it requires alice approval >
- alice approves action 1
- alice creates a new Rule with the following definition: "any(2, space.owners)"
- alice sets the Rule ID 1 as AdminIntentId for the Space 1
- alice adds charlie to Space 1
- < check charlie is not added yet, since we require bob approval too >
- bob approves action 3
- < check charlie is now a space 1 owner >
- charlie adds dave as a space owner
- < check dave is not added yet >
- bob approves action 4
- < check dave is now a space 1 owner >

**Comment by backsapc** [comment]
@Pitasi close?
