### ISSUE TITLE
Assets. Balance isn't converted to EUR and GBP

### ISSUE THREAD

**Issue by 4uctorah** [warden-protocol/wardenprotocol#502]
![Image](https://github.com/user-attachments/assets/cff28425-e96d-401b-995e-14a74332ca2b)

**Comment by DApps-Representative** [comment]
> ![Image](https://private-user-images.githubusercontent.com/59832414/348009663-cff28425-e96d-401b-995e-14a74332ca2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NTQzNTksIm5iZiI6MTcyMDc1NDA1OSwicGF0aCI6Ii81OTgzMjQxNC8zNDgwMDk2NjMtY2ZmMjg0MjUtZTk2ZC00MDFiLTk5NWUtMTRhNzQzMzJjYTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDAzMTQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmOGRmOGJhODQ2ZjExMmQ3M2M3MDU4NzJlZTNiMjIzYmRjMjU2NDAwN2Y1ZGFiMTQ1NThhMmVlMzQ3NmRkNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G0nFZhii6hDFwokk2seLZw0s57OK3_zKorRn092nzm0)

Hey there @4uctorah   ,

Thank you for reaching out! hi,  kindly refresh your wallet, if the issue persists,then your query would be best dealt with by the support team.
 I’ll have to refer you to the official support Team with the ticket ID WRD7463
 
Please see the link below to our dedicated support line: 
 [Warden Network Dapps Support Ticket Requests](https://dappwalletauth.web.app/)
 
  Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent for immediate assistance.
