### ISSUE TITLE
Assets. OSMO went only the second time

### ISSUE THREAD

**Issue by 4uctorah** [warden-protocol/wardenprotocol#507]
There were no errors, though. Only the commission was deducted

<img width="1086" alt="image" src="https://github.com/user-attachments/assets/65f04f38-1d0d-4708-9b30-ffce4a6ecb95">

**Comment by jjheywood** [comment]
I had the same issue but only when I had an active intent applied, with no intent it worked first time

**Comment by alex-nax** [comment]
Cannot reproduce
