### ISSUE TITLE
Intents. Transaction failed

### ISSUE THREAD

**Issue by 4uctorah** [warden-protocol/wardenprotocol#569]
![Image](https://github.com/user-attachments/assets/9d1b2111-561b-4a54-b8b6-5f21f95e0d29)

**Comment by alex-nax** [comment]
Cannot reproduce, possible that fixed in (https://github.com/warden-protocol/wardenprotocol/commit/d5f9f5f79dead9e2ff9e8c15145c0b69dccf3132#diff-733417c84bc3c18482c2307790397e32bfe419d8221d82b605b145f7b4f39af0R117)
