### ISSUE TITLE
Keplr mobile connection

### ISSUE THREAD

**Issue by laniakea42** [warden-protocol/wardenprotocol#580]
I can't connect via keplr mobile on https://spaceward.devnet.wardenprotocol.org/ - QR code doesn't appear
<img width="522" alt="e87c3f9a-c0ec-42a6-8b06-cd89d1db687a" src="https://github.com/user-attachments/assets/3eb66ae9-02fa-403b-b588-cbf11baf64c4">

**Comment by jjheywood** [comment]
I am going to close this issue as we will soon be replacing this with the EVM wallet connection
