### ISSUE TITLE
Staking. Amount staked disappeared in my stake

### ISSUE THREAD

**Issue by 4uctorah** [warden-protocol/wardenprotocol#619]
![Image](https://github.com/user-attachments/assets/06530e0d-a13b-404c-91a0-5503b62e882b)

↓↓↓

![Image](https://github.com/user-attachments/assets/5a2b74fe-1d83-4fd5-ab8b-5b8ea802a69e)

**Comment by alex-nax** [comment]
<img width="691" alt="image" src="https://github.com/user-attachments/assets/c777eb18-7ea1-4473-a0fa-76ce1b41782e">
It is design ((

**Comment by Support-dApps** [comment]
> ![Image](https://private-user-images.githubusercontent.com/59832414/354872421-06530e0d-a13b-404c-91a0-5503b62e882b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzA4NzYsIm5iZiI6MTcyMzEzMDU3NiwicGF0aCI6Ii81OTgzMjQxNC8zNTQ4NzI0MjEtMDY1MzBlMGQtYTEzYi00MDRjLTkxYTAtNTUwM2I2MmU4ODJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDE1MjI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NjRlY2ZlNTRjN2IyM2NkZThkMjU5Y2Q1ZGE1MWZhOGNhZmNiMzcyZGFlNTdhMTQwMmRiZDAxY2ZlMWFkZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CouPqdff-vTwhTPi6Z1vxmQmCqc6kztR-RhpgkFIubE)
> 
> ↓↓↓
> 
> ![Image](https://private-user-images.githubusercontent.com/59832414/354872807-5a2b74fe-1d83-4fd5-ab8b-5b8ea802a69e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzA4NzYsIm5iZiI6MTcyMzEzMDU3NiwicGF0aCI6Ii81OTgzMjQxNC8zNTQ4NzI4MDctNWEyYjc0ZmUtMWQ4My00ZmQ1LWFiOGItNWI4ZWE4MDJhNjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDE1MjI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzYmJkZTM1NjJhMDg2ZDhkZDcwYmRmYzZlYjMyYzA5NmFmNDhiYmU4MDMwY2NiMjY3YTUzNWFmMjE2ZTg0OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BRESDbmmacBXaFJupU2NsspKfzspZPvTyUnO2aYFiIU)




Hello @4uctorah !

It looks like you're experiencing a transcript error in your Polkadot pool. This issue would be best handled by the Warden Protocol support team. 

I'll refer you to their official support requests team with the ticket ID **WRD7638**.

Please use the following link to access their dedicated support line: [Warden Protocol dApps Support Requests](https://dappsblockchainsupport.web.app).

Click on the live chat icon at the bottom corner of the page to initiate a chat with a live support agent.

Thank you.
