### ISSUE TITLE
Spaceward: staking's validators list glitch

### ISSUE THREAD

**Issue by pitasi** [warden-protocol/wardenprotocol#667]
I see the table for validators with some visual issues on column sizes:

<img width="890" alt="image" src="https://github.com/user-attachments/assets/4b26f1f4-b4ac-4921-8937-cfd3193aba76">

**Comment by jjheywood** [comment]
@Pitasi could you share what size your browser window is please?

**Comment by pitasi** [comment]
> @Pitasi could you share what size your browser window is please?

I think that my width is 1215px or something like that
