### ISSUE TITLE
Update inference for warden-ai API v3

### ISSUE THREAD

**Issue by jjheywood** [warden-protocol/wardenprotocol#693]
There have been some updates made to the warden-ai API for passing an array of token names and returns price predictions for these tokens which then need to be verified. The updates to the API can be found here:

https://github.com/warden-protocol/warden-ai/blob/3a71b49a67ff9562d522af17797c350ce2fdac8d/src/flamingo/v3/schemas.py#L6
https://github.com/warden-protocol/warden-ai/blob/3a71b49a67ff9562d522af17797c350ce2fdac8d/src/flamingo/v3/api.py#L16

and from what I understand would need to be updated here:

 https://github.com/warden-protocol/wardenprotocol/blob/ai-abci-2.0/proto/warden/warden/v1beta3/inference.proto

**Comment by artur-abliazimov** [comment]
https://github.com/warden-protocol/wardenprotocol/blob/ai-abci-2.0/warden/app/inference/inference.go

**Comment by backsapc** [comment]
Current API /job/solve 

Request:
```
{
  "data": [10,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
}
```
Response
```
{
  "data": [3,7,11],
  "receipt": "BgAAAAAAAABguOpibzboUJZwI44="
}
```
v3 API

Request
```
{
  "solverInput": {
    "tokens": [
      "tkn1",
      "tkn2",
      "tkn3"
    ],
    "adversaryMode": false
  },
  "expectedItems": 3,
  "falsePositiveRate": 0.01
}
```
Response
```
{
  "solverOutput": {
    "forecasts": {
      "tkn1": 1.23,
      "tkn2": 4.56,
      "tkn3": 7.89
    }
  },
  "solverReceipt": "BgAAAAAAAADYxCJU"
}
```
