### ISSUE TITLE
6 - [x/act V2]: Consider unlinking Votes and Actions

### ISSUE THREAD

**Issue by artur-abliazimov** [warden-protocol/wardenprotocol#802]
We need to find a solution to address this:

![Image](https://github.com/user-attachments/assets/4f8eed44-6b2b-416e-8682-6d060604ab42)
![Image](https://github.com/user-attachments/assets/9f92720c-1b52-41a4-97c3-c814da5bec2e)

**Comment by backsapc** [comment]
@Pitasi I tried to estimate the gas needed for the transaction by using `AnteHandlers` and sending transactions on the local network, but I couldn't see a significant impact from the growing act. In my opinion, the attacker would end up spending much more gas than it would take to make the transaction too expensive. So, we could move this task to the backlog, as it's not necessary to implement it right now.

**Comment by pitasi** [comment]
yes let's put it in the backlog, I don't think that it's particular relevant right now
