### ISSUE TITLE
Old analyzer contract addresses on devnet

### ISSUE THREAD

**Issue by alex-nax** [warden-protocol/wardenprotocol#820]
got error "failed to execute message; message index: 0: executing contract: address warden14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9srt30us: no such contract [!cosm!wasm/wasmd@v0.51.0/x/wasm/types/errors.go:153]: analyzer error [/warden/warden/x/warden/keeper/rules.go:81]: no rule registry handler registered for message type" while trying to send assets on devnet

**Comment by jlehtimaki** [comment]
Hey @alex-nax ,

I've redeployed the contracts:
- ethereum_analyzer deployed at "warden14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9srt30us"
- osmosis_analyzer  deployed at "warden1nc5tatafv6eyq7llkr2gv50ff9e22mnf70qgjlv737ktmt4eswrq075d7k"
- basic_analyzer  deployed at "warden17p9rzwnnfxcjp32un9ug7yhhzgtkhvl9jfksztgw5uh69wac2pgsh92ghj"

Please let me know if they are not working as expected

**Comment by jjheywood** [comment]
@alex-nax is this resolved now?
