### ISSUE TITLE
Keys. MPC key isn't created

### ISSUE THREAD

**Issue by 4uctorah** [warden-protocol/wardenprotocol#859]
https://github.com/user-attachments/assets/e3de4952-3657-4cad-816e-f9c2637dc360

**Comment by jjheywood** [comment]
@4uctorah did this key ever get created? Sometime it takes a bit longer and you can see all the pending transaction in the sidebar

**Comment by 4uctorah** [comment]
> @4uctorah did this key ever get created? Sometime it takes a bit longer and you can see all the pending transaction in the sidebar

Never. It’s stay here forever on devnet
<img width="444" alt="image" src="https://github.com/user-attachments/assets/cbc65cb3-297b-475e-a501-c38c189ac948">
