### ISSUE TITLE
The cross in popups isn't in the right place

### ISSUE THREAD

**Issue by 4uctorah** [warden-protocol/wardenprotocol#865]
![Image](https://github.com/user-attachments/assets/f080acc7-1ef1-4f12-96e2-aeedd1d51ac6)
![Image](https://github.com/user-attachments/assets/6ab820cc-520a-4647-959e-66dc8efc8b83)
![Image](https://github.com/user-attachments/assets/d143cfaa-a686-452c-8d46-a08200cfb085)
![Image](https://github.com/user-attachments/assets/fe0cb9b1-50f9-429b-b7da-bc779d97342b)

**Comment by alex-nax** [comment]
Not a bug https://github.com/orgs/warden-protocol/projects/13?pane=issue&itemId=74639625
