### ISSUE TITLE
Connect X account button not responsive

### ISSUE THREAD

**Issue by arize99** [warden-protocol/wardenprotocol#926]
The Connect to your X account in [Warden Protocol](https://quests.wardenprotocol.org/) is not responsive. My Chrome is up to date, I connected with my MetaMask, and I have linked other accounts (Telegram, Discord, and Cosmos), but the Connect to your X account is not responsive despite my active login on X.

![connect x not responsive](https://github.com/user-attachments/assets/016e98e5-c094-402c-af1b-ed7af13637a8)

**Comment by jjheywood** [comment]
This issue is not related to this repo
